services:

  errorpages:
    image: nginx:alpine
    volumes:
      - ./error-pages:/usr/share/nginx/html:ro
    networks:
      - gateway-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.errorpages.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.errorpages.entrypoints=web"
      - "traefik.http.services.errorpages.loadbalancer.server.port=80"


  traefik:
    image: traefik:v3.5
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gateway-network
    labels:
      - "traefik.enable=true"

      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`ops.localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"

      # Middleware global de errores
      - "traefik.http.middlewares.global-errors.errors.status=400-599"
      - "traefik.http.middlewares.global-errors.errors.service=errorpages"
      - "traefik.http.middlewares.global-errors.errors.query=/{status}.html"

      # Router global que atrapa todo
      - "traefik.http.routers.catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.catchall.entrypoints=web"
      - "traefik.http.routers.catchall.middlewares=global-errors"
      - "traefik.http.routers.catchall.service=errorpages"


  neo4j:
    image: neo4j:5.22.0-community
    restart: always
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    volumes:
      - neo4j_data:/data
      - ./import:/import
    networks:
      - gateway-network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    networks:
      - gateway-network
    labels:
      - "traefik.enable=true"

      # API disponible en api.localhost/api/
      - "traefik.http.routers.backend.rule=Host(`api.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

      # Middleware stripPrefix
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"

      # Middleware rateLimit (máx 5 req/s por cliente)
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=10"

      # Middleware errors
      - "traefik.http.middlewares.api-errors.errors.status=400, 404, 502"
      - "traefik.http.middlewares.api-errors.errors.service=errorpages"
      - "traefik.http.middlewares.api-errors.errors.query=/{status}.html"

      # Aplica el middleware junto a los otros
      - "traefik.http.routers.backend.middlewares=strip-api,api-ratelimit,api-errors"

volumes:
  neo4j_data:
    driver: local

networks:
  gateway-network:
    driver: bridge
